### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by Riddler76** [unturnedROCKS/Kits#4]
Hey,

Why  do you remove cooldown? when using other permission system we can't set cooldown :/

**Comment by fr34kyn01535** [comment]
Cooldown should work in all permission systems

**Comment by Riddler76** [comment]
Ok, so in my configuration i use LPX permission system.

How can i add cooldown on command ?

**Comment by fr34kyn01535** [comment]
I don't know how lpx does it, but it HAS to implement cooldown

**Comment by Riddler76** [comment]
> Cooldown should work in all permission systems 
> _(If plugin is update and if the developper know the rocket update)_

I think, is not a good idea, to do critical update, all developers are not ready and don't have information of this update . . . It HAS to implement cooldown, yes is sure ^^ But need time to do it.
Need to stop doing critical update, without preventing Dev & User. Why don't use the forum in this case ?

In this time server owner can't provide good service to her player.

Why don't do an option for enable or disable cooldown ?

**Comment by fr34kyn01535** [comment]
#1 you don't have to enable updates
#2 there is no need to update until friday, thats 4 days to implement, way more time then i have to cope with nelsons surprising changes

**Comment by Riddler76** [comment]
<3 Nelson's Surprise ^^
Now i need to wait LPX update :((( 8 Servers without perm :/

Have a nice day.
